version: 2.1
jobs:
  custom-version-*:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run:
          name: Build the bundle files
          command: |
            echo 'Building the bundle!'
            echo 'This is the delivery pipeline'
