# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

branches: &branches
  filters:
    branches:
      only:
        - /custom-version-.*/
      ignore:
        - master

version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  windows: # This is the name of the build
    executor: win/default
    working_directory: ~/repo
    steps:
      - checkout # Checks out our code from Bitbucket and installs dependencies
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: set DEVELOPMENT=$DEVELOPMENT
      - run: set UNSIGNED=$UNSIGNED # Signing the App will fail, so remove this build step
      - run: set SERVER_NAME=$SERVER_NAME
      - run: set CHANNEL_ID=$CHANNEL_ID
      - run:
          name: Publish the current version
          command: npm run publish-js
  mac:
    macos: # Build the Mac Version
      xcode: 11.3.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Publish the current version
          command: DEVELOPMENT=$DEVELOPMENT SERVER_NAME=$SERVER_NAME CHANNEL_ID=$CHANNEL_ID UNSIGNED=$UNSIGNED npm run publish-js

workflows:
  version: 2.1

  build-workflows:
    jobs:
      - windows
        #  <<: *branches
      - mac
        #  <<: *branches

