import { TestResult } from "../../../interfaces";

export interface Site {
  app: string;
  url: string;
  email: string;
  password: string;
  testResults?: TestResult[];
  allTestsFinished?: boolean;
}

export const sites: Site[] = [
  {
    app: "G-Suite",
    url: "https://gsuite.google.com/",
    email: "",
    password: "",
  },
  {
    app: "Smartlook",
    url: "https://www.smartlook.com/sign/in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Agora",
    url: "https://app.agorapulse.com/auth/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Eclincher",
    url: "https://app.eclincher.com/ec/login",
    email: "fabrice.schoenebergertest@gmail.com",
    password: "!12345678!Aa",
  },
  {
    app: "Typeform",
    url: "https://admin.typeform.com/login/",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Miro",
    url: "https://miro.com/login/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Glisser",
    url: "https://presenter.glisser.com/#/signin",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "All Seated",
    url: "https://www.web.allseated.com/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "E-Sign",
    url: "https://app.e-sign.co.uk/#/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Wunderlist",
    url: "https://www.wunderlist.com/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Go Squared",
    url: "https://www.gosquared.com/login/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Slack",
    url: "https://slack.com",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "EventBrite",
    url: "https://www.eventbrite.com/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "AppCues",
    url: "https://auth.appcues.com/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "EventZilla",
    url: "https://www.eventzilla.net/us/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "FreedCamp",
    url: "https://freedcamp.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "GetAccept",
    url: "https://app.getaccept.com/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "EverSign",
    url: "https://eversign.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "BuzzSumo",
    url: "https://app.buzzsumo.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Calendly",
    url: "https://calendly.com/login",
    email: "test123@vipfy.store",
    password: "2020Vipfy!",
  },
  {
    app: "Wrike",
    url: "https://www.wrike.com/login/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Buffer",
    url: "https://buffer.com/signin",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Freshbooks",
    url: "https://my.freshbooks.com/#/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Docusign",
    url: "https://account.docusign.com/logout#/username",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "ActiveCampaign",
    url: "https://www.activecampaign.com/login/",
    email: "testing@vipfy.store",
    password: "2020Vipfy!",
  },
  {
    app: "Moo",
    url: "https://www.moo.com/uk/account/signin.php",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "CreateSend",
    url: "https://login.createsend.com/l",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Asana",
    url: "https://app.asana.com/-/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "AgileCRM",
    url: "https://my.agilecrm.com/enter-domain?to=login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Trello",
    url: "https://trello.com/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "SalesForce",
    url: "https://login.salesforce.com/",
    email: "test123-lygr@force.com",
    password: "2019Vipfy!",
  },
  {
    app: "Meraki",
    url: "https://account.meraki.com/secure/login/dashboard_login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Brand24",
    url: "https://app.brand24.com/user/login/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Expensify",
    url: "https://www.expensify.com/signin",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "SendGrid",
    url: "https://app.sendgrid.com/login",
    email: "Vipfy3",
    password: "2019Vipfy!",
  },
  {
    app: "Intermedia",
    url: "https://cp.intermedia.net/ControlPanel/Login",
    email: "office@vipfy.com",
    password: "Vipfy.Store1234!",
  },
  {
    app: "Webex",
    url: "https://idbroker.webex.com/idb/IdBGlobalLogin",
    email: "test123@vipfy.store",
    password: "Qwerty123!",
  },
  {
    app: "certify",
    url: "https://www.certify.com/Login.aspx",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Confluence",
    url: "https://id.atlassian.com/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Grow",
    url: "",
    email: "",
    password: "",
  },
  {
    app: "Humanity",
    url: "https://www.humanity.com/app/",
    email: "test1234@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Ideanote",
    url: "https://app.ideanote.io/get-started/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Jell",
    url: "https://jell.com/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Klipfolio",
    url: "https://app.klipfolio.com/login",
    email: "test1234@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Qualaroo",
    url: "https://app.qualaroo.com/signin",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "ClickMeeting",
    url: "https://account-panel.clickmeeting.com/login",
    email: "test1234@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Mailchimp",
    url: "https://login.mailchimp.com",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Campaigner",
    url: "https://secure.campaigner.com/Login/",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Nutshell",
    url: "https://www.nutshell.com/login/",
    email: "test1234@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "SurveyGizmo",
    url: "https://app.surveygizmo.com/login/v1",
    email: "tester@vipfy.store",
    password: "mw7vSF2CbD5FgT6zif96AgGsNFJMQo",
  },
  {
    app: "GetResponse",
    url: "https://app.getresponse.com/login?lang=en",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Sisense",
    url: "https://www.sisense.com/u/login",
    email: "tester@vipfy.store",
    password: "Vipfy1234!",
  },
  {
    app: "YotPo",
    url: "https://yap.yotpo.com/#/login",
    email: "tester@vipfy.store",
    password: "HP9E^m)!Aq)^g9UN\u003eyuqiTR5_==AYb",
  },
  {
    app: "Qualtrics",
    url: "https://login.qualtrics.com/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Gusto",
    url: "https://app.gusto.com/login",
    email: "tester@vipfy.store",
    password: "eRJ3(6$7\u0026)!C*9\u0027AdwZ@2(R_SEZBKZ",
  },
  {
    app: "ConvertKit",
    url: "https://app.convertkit.com/users/login",
    email: "tester@vipfy.store",
    password: ")_N/PfqWo`{2)\u003c!7y6HYhSTfR\\\u00273]_",
  },
  {
    app: "SimilarWeb",
    url: "https://account.similarweb.com/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "DataBricks",
    url: "https://accounts.cloud.databricks.com/registration.html#login",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "Proposify",
    url: "https://app.proposify.com/login",
    email: "nvtester@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Customer.io",
    url: "https://fly.customer.io/login",
    email: "nvtester@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "DroneDeploy",
    url: "https://www.dronedeploy.com/app2/auth/signin",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "Data dog",
    url: "https://app.datadoghq.com/account/login",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "Twilio(2-step)",
    url: "https://www.twilio.com/login",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "Zendesk",
    url: "https://www.zendesk.com/login/",
    email: "testing@vipfy.store",
    password: "2020Vipfy!",
  },
  {
    app: "Shopify",
    url: "https://accounts.shopify.com/store-login",
    email: "test123@vipfy.store",
    password: "2020Vipfy!",
  },
  {
    app: "MuleSoft",
    url: "https://anypoint.mulesoft.com/home/",
    email: "osama_vipfy",
    password: "Vipfy.Store1234!",
  },
  {
    app: "OfficeVibe",
    url: "https://app.officevibe.com/#/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "HubDoc",
    url: "https://app.hubdoc.com/login",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "Rydoo",
    url: "https://accounts.rydoo.com/login",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "Zoom",
    url: "https://zoom.us/signin",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "Chargebee",
    url: "https://vipfy-test.chargebee.com",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store12345!",
  },
  {
    app: "Applitools",
    url: "https://applitools.com/users/login",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "TeamWork",
    url: "https://www.teamwork.com/launchpad/login",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "CloudFlare",
    url: "https://dash.cloudflare.com/login",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "LeadFeeder",
    url: "https://app.leadfeeder.com/f/sign/in",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "BeeKeeper",
    url: "https://start.beekeeper.io/login",
    email: "nvtester@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "JotForm",
    url: "https://eu.jotform.com/login",
    email: "vipfyTester",
    password: "2019Vipfy!",
  },
  {
    app: "SurveyMonkey",
    url: "https://de.surveymonkey.com/user/sign-in/",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "BaseCamp",
    url: "https://launchpad.37signals.com/signin",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Canva",
    url: "https://www.canva.com/login",
    email: "nvtester@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "Hubspot",
    url: "https://app.hubspot.com/login",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "LaunchDarkly",
    url: "https://app.launchdarkly.com/",
    email: "test123@vipfy.store",
    password: "2020Vipfy!",
  },
  {
    app: "Invision app",
    url: "https://projects.invisionapp.com/d/login",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "SendPulse",
    url: "https://login.sendpulse.com/login/",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "KissFlow",
    url: "https://app.kissflow.com/",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "FastSpring",
    url: "https://dashboard.fastspring.com/login.xml",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "G2Crowd",
    url: "https://www.g2.com/#state.email.showform",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "infusionsoft",
    url: "https://signin.infusionsoft.com/login",
    email: "test123@vipfy.store",
    password: "2020Vipfy!",
  },
  {
    app: "bamboohr",
    url: "https://app.bamboohr.com/login/",
    email: "nvtester@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Feedly",
    url: "https://feedly.com/v3/auth/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Pushover",
    url: "https://pushover.net/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Rezdy",
    url: "https://app.rezdy.com/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Recharge",
    url: "https://www.recharge.com/en/user/spree_user/sign_in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "BrickFTP",
    url: "https://app.files.com/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "CastingWords",
    url: "https://castingwords.com/store/customer/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "opesta",
    url: "https://app.opesta.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Ziggeo",
    url: "https://ziggeo.com/signin",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Bl.ink",
    url: "https://app.bl.ink/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "eEndorsements",
    url: "https://eendorsements.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "BuySellAdds",
    url: "https://www.buysellads.com/users/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "SharpCloud",
    url: "https://my.sharpcloud.com/html/#/signin",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "ExpressPigeon",
    url: "https://expresspigeon.com/access/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "StoryChief",
    url: "https://app.storychief.io/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Vervoe",
    url: "https://vipfy.vervoe.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "RowShare",
    url: "https://my.rowshare.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "shipcloud",
    url: "https://app.shipcloud.io/en/users/sign_in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "detectify",
    url: "https://detectify.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "EasyPromos",
    url: "https://admin.easypromosapp.com",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "TimeHero",
    url: "https://app.timehero.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "timekit",
    url: "https://admin.timekit.io/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Appdrag",
    url: "https://prod.appdrag.com/Login.html#",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "teamgram",
    url: "https://www.teamgram.com/login",
    email: "nvtester",
    password: "2018Vipfy!",
  },
  {
    app: "DocDroid",
    url: "https://www.docdroid.net/login",
    email: "nvtestervipfystore",
    password: "2018Vipfy!",
  },
  {
    app: "LeadAbode",
    url: "https://dashboard.leadabode.com/login",
    email: "testmail147@abv.bg",
    password: "sfz7S9Te",
  },
  {
    app: "MediaToolkit",
    url: "https://www.mediatoolkit.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "WeekDone",
    url: "https://weekdone.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Retently",
    url: "https://app.retently.com/account/login",
    email: "nvtester@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "playnyo",
    url: "https://www.planyo.com/login/login.php",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Dribbble",
    url: "https://dribbble.com/session/new",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Sellsy",
    url: "https://login.sellsy.com/login",
    email: "test123@vipfy.store",
    password: "4b8d7baa305e",
  },
  {
    app: "Fulcrum",
    url: "https://web.fulcrumapp.com/users/sign_in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Callingly",
    url: "https://callingly.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Printavo",
    url: "https://www.printavo.com/users/sign_in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Flowdock",
    url: "https://www.flowdock.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Repsly",
    url: "https://user.repsly.com/account/logon",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Artibots.AI",
    url: "https://app.artibot.ai/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Call hub",
    url: "https://app.callhub.io/login/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Nicereply",
    url: "https://admin.nicereply.com/admin/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "SupportBee",
    url: "https://vipfy5.supportbee.com/members/sign_in",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Tallyfy",
    url: "https://go.tallyfy.com/api/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "JumpLead",
    url: "https://profile.jumplead.com/session/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Docupilot",
    url: "https://dashboard.docupilot.app/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Vextras",
    url: "https://app.vextras.com/auth/login",
    email: "nvtester@vipfy.store",
    password: "HaBe4TTGAj703s4Oq72lV8b3MDXr93yZ",
  },
  {
    app: "eTermin",
    url: "https://www.etermin.net/Login.aspx",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "BeanStalk",
    url: "https://login.beanstalkapp.com/session/new",
    email: "VipfyTester",
    password: "2018Vipfy!",
  },
  {
    app: "MoonMail",
    url: "https://dashboard.moonmail.io/",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Stripe",
    url: "https://dashboard.stripe.com/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Wufoo",
    url: "https://secure.wufoo.com/login/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Podio",
    url: "https://podio.com/login?force_locale=en_US",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Discord",
    url: "https://discordapp.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "FreshDesk",
    url:
      "https://accounts.freshworks.com/login?client_id=3739452e-e3dc-4f7f-9aaa-739acb9cbcb9\u0026logout_uri=https%3A%2F%2Fvipfyhelp.freshdesk.com%2Ffreshid%2Flogout\u0026redirect_uri=https%3A%2F%2Fvipfyhelp.freshdesk.com%2Ffreshid%2Fauthorize_callback\u0026su=true",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Mindmeister",
    url: "https://www.mindmeister.com/account/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Teachable",
    url: "https://sso.teachable.com/secure/teachable_accounts/sign_in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Cognito Forms",
    url: "https://www.cognitoforms.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Pocket",
    url: "https://getpocket.com/login?e=4",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "smartsheet",
    url: "https://app.smartsheet.com/b/home",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Schedule Once",
    url: "https://account.oncehub.com/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Webflow",
    url: "https://webflow.com/dashboard/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Insightly",
    url: "https://login.insightly.com/User/Login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Mailerlite",
    url: "https://app.mailerlite.com/users/login/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Harvest",
    url: "https://id.getharvest.com/harvest/sign_in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Chatwork",
    url: "https://www.chatwork.com/",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "LionDesk",
    url: "https://www.liondesk.com/admin/login.html",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "WebMerge",
    url: "https://www.webmerge.me/manage/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "SendinBlue",
    url: "https://app.sendinblue.com/account/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "FormStack",
    url: "https://www.formstack.com/admin/user/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "wave",
    url: "https://my.waveapps.com/login/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Thinkific",
    url: "https://vipfy-s-school.thinkific.com/users/sign_in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "YouCanBook.me",
    url: "https://app.youcanbook.me/#/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "One Signal",
    url: "https://app.onesignal.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "LiveChat",
    url: "https://accounts.livechatinc.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "MailGun",
    url: "https://app.mailgun.com/sessions/new",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Click Up",
    url: "https://app.clickup.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Pipefy",
    url: "https://app-auth.pipefy.com/login?afterLoginRedirectTo=",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Dubsado",
    url: "https://hello.dubsado.com/user/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Klaviyo",
    url: "https://www.klaviyo.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Rescue time",
    url: "https://www.rescuetime.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Gumroad",
    url: "https://gumroad.com/#login?next=%2Fdashboard",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Reddit",
    url: "https://www.reddit.com/login/",
    email: "VipfyTester",
    password: "2018Vipfy!",
  },
  {
    app: "meetup",
    url: "https://secure.meetup.com/login/",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Process Street",
    url: "https://app.process.st/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Zoho Forms",
    url:
      "https://accounts.zoho.eu/signin?servicename=ZohoForms\u0026signupurl=https://www.zoho.eu/forms/signup.html",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Knack",
    url: "https://builder.knack.com",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Paper Form",
    url: "https://paperform.co/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "123FormBuilder",
    url: "https://www.123formbuilder.com/index.php?p=login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Contactually",
    url: "https://www.contactually.com/users/sign_in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Clearbit",
    url: "https://dashboard.clearbit.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "soundcloud",
    url: "https://soundcloud.com/signin",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Clio",
    url: "https://eu.app.clio.com/session/new",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "CloudConvert",
    url: "https://cloudconvert.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "MailParser",
    url: "https://app.mailparser.io/account/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Patreon",
    url: "https://www.patreon.com/login?ru=%2F",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Bonjoro",
    url: "https://www.bonjoro.com/auth/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "PomoDoneApp",
    url: "https://my.pomodoneapp.com/?_ga=2.115982598.1225596426.1551189708-453154309.1551189708",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "mailjet",
    url: "https://app.mailjet.com/signin",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Purechat",
    url: "https://purechat.com",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Realvolve",
    url: "https://njpow.realvolve.com/users/sign_in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "10to8 Online Booking",
    url: "https://10to8.com/my/user/login/?next=/account/organisations/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "LandBot",
    url: "https://app.landbot.io/signin/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Formsite",
    url: "https://fs10.formsite.com/form_app/FormSite?FormId=LoadLogin",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "invoice ninja",
    url: "https://app.invoiceninja.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Bitly",
    url: "https://bitly.com/a/sign_in",
    email: "VipfyTester",
    password: "2018Vipfy!",
  },
  {
    app: "Pivotal Tracker",
    url: "https://www.pivotaltracker.com/signin",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "text magic",
    url: "https://my.textmagic.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Mail Shake",
    url: "https://mailshake.com/app/#/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Privy",
    url: "https://dashboard.privy.com/users/sign_in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Product Board",
    url: "https://app.productboard.com",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Quotient",
    url: "https://go.quotientapp.com/sign-in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Delighted",
    url: "https://delighted.com/signin",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Appointlet",
    url: "https://www.appointlet.com/account/login/",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Toodledo",
    url: "https://www.toodledo.com/signin.php",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Repair Shopr",
    url: "https://vipfy.repairshopr.com/users/sign_in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "vCita",
    url: "https://www.vcita.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Trust Pilot",
    url: "https://www.trustpilot.com/users/connect?redirect=%2Fusers%2Flogin",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Strava",
    url: "https://www.strava.com/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Wistia",
    url: "https://vipfy.wistia.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Cyfe",
    url: "https://app.cyfe.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Remember the Milk",
    url: "https://www.rememberthemilk.com/login/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Wealth Box CRM",
    url: "https://app.crmworkspace.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Practice Ignition",
    url: "https://app.practiceignition.com/sign-in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Powr Form Builder",
    url: "https://www.powr.io",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Ryver",
    url: "https://vipfy2.ryver.com/application/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Discus",
    url: "https://disqus.com/profile/login/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Woodpecker.co",
    url: "https://app.woodpecker.co/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Wachete",
    url: "https://www.wachete.com/sign-in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "MoonClerk",
    url: "https://app.moonclerk.com/signin",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Mighty Networks",
    url: "https://vipfytesting.mn.co/sign_in",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Instapaper",
    url: "https://www.instapaper.com",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Mailmunch",
    url: "https://app.mailmunch.co/users/sign_in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "SignRequest",
    url: "https://signrequest.com/#/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "ticket tailor",
    url: "https://www.tickettailor.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Service M8",
    url: "https://www.servicem8.com/eu/login-page",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "DocParser",
    url: "https://app.docparser.com/account/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Envoy",
    url: "https://dashboard.envoy.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Setmore Appointment",
    url: "https://my.setmore.com/",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Workable",
    url: "https://www.workable.com/auth/shield",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Giphy",
    url: "https://giphy.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Wootric",
    url: "https://app.wootric.com",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "PDF filler",
    url: "https://www.pdffiller.com/en/login.htm",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "DocSend",
    url: "https://docsend.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Nimble",
    url:
      "https://app.nimble.com/?_ga=2.70824215.681660228.1551711705-833687642.1551711705#login/enter",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Mixpanel",
    url: "https://mixpanel.com/login/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Limo Anywhere",
    url: "https://manage.mylimobiz.com/admin/login.asp",
    email: "",
    password: "",
  },
  {
    app: "Outgrow",
    url: "https://app.outgrow.co/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Pagerduty",
    url: "https://vipfy.pagerduty.com/sign_in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Podia",
    url: "https://www.podia.com/login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Postmark",
    url: "https://account.postmarkapp.com/login",
    email: "vipfytester",
    password: "2019Vipfy!",
  },
  {
    app: "Paymo",
    url: "https://app.paymoapp.com/auth/login/",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Revue",
    url: "https://www.getrevue.co/users/sign_in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "getsitecontrol",
    url: "https://app.getsitecontrol.com/#/sign-in",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Rebrandly",
    url:
      "https://oauth.rebrandly.com/account/login?returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DACB648C3-A865-4D0B-BB95-69299AA63556%26redirect_uri%3Dhttps%253A%252F%252Fapp.rebrandly.com%26state%3D%257B%2522path%2522%253A%2522%252Flinks%2522",
    email:
      "%2522search%2522%253A%2522%2522%257D%26response_type%3Dtoken%26scope%3Drbapi%2520rbapikeys%2520rbinvites%2520rbdowngrade",
    password: "nvtester@vipfy.store",
  },
  {
    app: "Caspio",
    url: "https://id.caspio.com/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Airtable",
    url: "https://airtable.com/login",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "Todoist",
    url: "https://todoist.com/seeYou",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "Evernote",
    url: "https://www.evernote.com/Login.action",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "AcuityScheduling",
    url: "https://secure.acuityscheduling.com/login.php",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "Pintrest",
    url: "https://www.pinterest.de/login/",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "Jira",
    url: "https://id.atlassian.com/login",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "LeanKit",
    url: "https://vipfy6431.leankit.com/Account/Membership/Login",
    email: "nvtester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Demio",
    url: "https://my.demio.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "LiveStorm",
    url: "https://app.livestorm.co/#/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "flock",
    url: "https://web.flock.com/?S38IyyEH7wAeof8Z=",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Email Octopus",
    url: "https://emailoctopus.com/account/sign-in",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "One page CRM",
    url: "https://secure.onepagecrm.com",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Active Collab",
    url: "https://activecollab.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Apify",
    url: "https://my.apify.com/sign-in",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "MongoDB",
    url: "https://cloud.mongodb.com/user#/atlas/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Redbooth",
    url: "https://redbooth.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Parseur",
    url: "https://app.parseur.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Book Like a Boss",
    url: "https://bookme.name/auth/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Promoter.io",
    url: "https://app.promoter.io/account/login/",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "textlocal",
    url: "https://control.txtlocal.co.uk",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Kanban Flow",
    url: "https://kanbanflow.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "SendOwl",
    url: "https://www.sendowl.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Free Agent",
    url: "https://vipfy.freeagent.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Accelo",
    url: "https://vipfy-testing.accelo.com/",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "cliengo",
    url: "https://app.cliengo.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "geckoboard",
    url: "https://app.geckoboard.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "sendpulse",
    url: "https://login.sendpulse.com/login/",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Donately ",
    url: "https://dash.donately.com",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Beeminder",
    url: "https://www.beeminder.com/users/sign_in",
    email: "VipfyTester",
    password: "2018Vipfy!",
  },
  {
    app: "Skedda",
    url: "https://www.skedda.com/account/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "StatusCake",
    url: "https://app.statuscake.com/Login/",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "money bird",
    url: "https://moneybird.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Dasheroo",
    url: "https://www.dasheroo.com/sign_in",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "FormKeep",
    url: "https://formkeep.com/session/new",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Lob",
    url: "https://dashboard.lob.com/#/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Submittable",
    url: "https://manager.submittable.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "AdRoll",
    url: "https://app.adroll.com/account/signin",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Ninox",
    url: "https://ninoxdb.de/en/",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Accredible Certificates",
    url: "https://dashboard.accredible.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Runrun.it",
    url: "https://runrun.it/en-US/user_session/new",
    email: "tester@vipfy.store",
    password: "2018Vipfy!5(E\u003cfo=bJ6wX5270",
  },
  {
    app: "NeverBounce",
    url: "https://app.neverbounce.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "StockTwits",
    url: "https://stocktwits.com/",
    email: "vipfytester",
    password: "2019Vipfy!",
  },
  {
    app: "Poptin",
    url: "https://app.popt.in/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "timecamp",
    url: "https://www.timecamp.com/auth/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Toggl",
    url: "https://toggl.com/login/",
    email: "osama.haroon@vipfy.store",
    password: "Vipfy.Store1234!",
  },
  {
    app: "Untappd",
    url: "https://untappd.com/login",
    email: "VipfyTester",
    password: "2018Vipfy!",
  },
  {
    app: "Phaxio",
    url: "https://console.phaxio.com/sf_guard_users/sign_in",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Nozbe",
    url: "https://app.nozbe.com/#login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "GetProspect",
    url: "https://getprospect.io/app/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Crisp",
    url: "https://app.crisp.chat/initiate/login/",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Chatra",
    url: "https://app.chatra.io",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Elopage",
    url: "https://elopage.com/users/sign_in",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "RightSignature",
    url: "https://rightsignature.com/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Mavenlink",
    url: "https://app.mavenlink.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Formcarry",
    url: "https://formcarry.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "iContact",
    url: "https://www.icontact.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Kanbantool",
    url: "https://vipfy.kanbantool.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Quaderno",
    url: "https://quadernoapp.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Clickatel",
    url: "https://portal.clickatell.com/#/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "smsfactor",
    url: "https://secure.smsfactor.com",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "lime-go",
    url: "https://go.lime-go.com",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "weekplan",
    url: "https://next.weekplan.net/#/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "brandquiz",
    url: "https://app.brandquiz.io/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "ActionNet",
    url: "https://actionnetwork.org/users/sign_in",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "breezyHR",
    url: "https://app.breezy.hr/signin",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "liquidPlanner",
    url: "https://app.liquidplanner.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Chartmogul",
    url: "https://app.chartmogul.com/users/sign_in",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "prodpad",
    url: "https://app.prodpad.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "kickofflabs",
    url: "https://app.kickofflabs.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Vision6",
    url: "https://app.vision6.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "recruitee",
    url: "https://auth.recruitee.com",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "WisePops",
    url: "https://app.wisepops.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "memberful",
    url: "https://vipfy.memberful.com/admin/auth/sign_in",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Manuscript",
    url: "https://vipfy.manuscript.com/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Toky",
    url: "https://app.toky.co/login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "CompanyCam",
    url: "https://app.companycam.com/users/sign_in",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Textline",
    url: "https://application.textline.com/auth/sign_in",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "riddle",
    url: "https://www.riddle.com/user/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "DonorBox",
    url: "https://donorbox.org/org_session/new",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "skedpal",
    url: "https://app.skedpal.com/#/login",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "rocketreach",
    url: "https://rocketreach.co/login",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "autoklose",
    url: "https://app.autoklose.com/login",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Booking",
    url:
      "https://account.booking.com/sign-in?op_token=EgVvYXV0aCLFBAoUdk8xS2Jsazd4WDl0VW4yY3BaTFMSCWF1dGhvcml6ZRo1aHR0cHM6Ly9zZWN1cmUuYm9va2luZy5jb20vbG9naW4uaHRtbD9vcD1vYXV0aF9yZXR1cm4q5ANVdWdDd25PWWdBUWlvNm5DX2hReUlZN3kyQWtmUXNubG01NmZKcWgyYTQ1NzU2alNzQ1UxNGM0V3VudlFCY3l1RG94eDhZWXRzZzZMNHVTZ3QzcGRCbTdzMk15VDFQNWtlOGdaeExVS25YMzc5Y2RqLXFTQUs5cFhYYXk0VGhKMFhFVVE3Y0FuZF9DUV8wdndHYXcydmp5WEJYSmxwb3dNaEdfN3NjY1dMVEozVWNZWF9rYWJZejREQm15SnJBYVJvWm5IMnF3NEVwRm5OTWRjZzRsZHRwZWloQUdSNktqT1BhNEVqMExoZHdaWnpFSFJPYldGaFB2YlJoS3BTcTJmakVoSlZNQUkxWERtQ2VQOWxHNk9KYnZ3Y3FpeWRMMm1HOW9oUnd4bmZiMWlXVUFVQmE3akFxeng5RUVhZHBaUW1IWmk0QWNaUzF1R3ZuQzFwdEZnb09nM2RyM2hHcUc0S2VnU19BZ3d1QkVIY0NndjNpNnJzS2lSTVlBbzJ4NEZYdmM0RHltTkRhbmZfdXJ6WXJfNkE1RmhVNGN6MVh5VUlfZHFlYlhjaWxibWl5WGxjUmVCU251Y3U1eHV3WFd5VjVWX19sOVpoVU5OdHd1dlpHbjZ4NERlVjhEMGRabTlzRTdJQgRjb2RlKhIImqIYEAMw-bOt5-KuIzoAQgA",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Ebay",
    url: "https://signin.ebay.com/ws/eBayISAPI.dll?SignIn",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Twitter",
    url: "https://twitter.com/login",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Amazon",
    url:
      "https://www.amazon.com/ap/signin?_encoding=UTF8\u0026ignoreAuthState=1\u0026openid.assoc_handle=usflex\u0026openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select\u0026openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select\u0026openid.mode=checkid_setup\u0026openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0\u0026openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0\u0026openid.pape.max_auth_age=0\u0026openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fref%3Dnav_signin\u0026switch_account=",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "idealo",
    url: "https://business.idealo.com/en/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Balsamic",
    url: "https://balsamiq.cloud/#login",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Alibaba",
    url: "https://passport.alibaba.com/icbu_login.htm?return_url=http%3A%2F%2Fus.my.alibaba.com",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Deutsche Bahn",
    url:
      "https://fahrkarten.bahn.de/cache/start/start.post?lang=en\u0026scope=login\u0026dbkanal_007=L04_S02_D002_KIN0059_TOP-NAVI-LOGIN_LZ01#stay",
    email: "MarcEtting",
    password: "2018Vipfy!",
  },
  {
    app: "Groupon",
    url: "https://www.groupon.com/login?return_to=https%3A%2F%2Fwww.groupon.com%2F",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "istockphoto",
    url: "https://www.istockphoto.com/de/en/sign-in?returnurl=%2Fde%2Fen%2F",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "outbrain",
    url: "https://my.outbrain.com/login",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "SAP",
    url: "https://www.sap.com/index.html",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "shutterstock",
    url: "https://accounts.shutterstock.com/login",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Vimeo",
    url: "https://vimeo.com/log_in",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Quora",
    url: "https://de.quora.com",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Avaza",
    url: "https://vipfy.avaza.com/Account/Login",
    email: "tester@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Device Magic",
    url: "https://www.devicemagic.com/users/login",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Site 24*7",
    url:
      "https://accounts.zoho.eu/signin?servicename=Site24x7\u0026serviceurl=%2Flogin%2Fsuccess.jsp\u0026portal_name=Site24x7\u0026signupurl=https%3A%2F%2Fwww.site24x7.eu%2Fsignup.html%3Fpack%3D44%26l%3Den",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "new relic",
    url: "https://login.newrelic.com/login",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "enalyzer",
    url: "https://www.enalyzer.com/#sidemenu=sign.in",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "robly",
    url: "https://app.robly.com/login",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "parserr",
    url: "https://parserr.com/account/Login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "egnyte",
    url: "https://vipfy.egnyte.com/#login",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "deepcrawl",
    url: "https://app.deepcrawl.com/login",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "SAP (artificial logon page)",
    url: "https://accounts.sap.com",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Ecwid",
    url: "https://my.ecwid.com/cp/",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "ZenDesk ",
    url:
      "https://vipfy562.zendesk.com/access/unauthenticated?return_to=https%3A%2F%2Fvipfy562.zendesk.com%2Fagent%2Fwelcome",
    email: "marc@vipfy.store",
    password: "2018Vipfy!",
  },
  {
    app: "Collect.Chat",
    url: "https://app.collect.chat/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "QuickBooks",
    url: "https://c34.qbo.intuit.com/qbo34/login",
    email: "test123@vipfy.store",
    password: "2019Vipfy!",
  },
  {
    app: "Grammarly",
    url: "https://www.grammarly.com/signin",
    email: "fabrice.schoenebergertest@gmail.com",
    password: "!12345678!",
  },
  {
    app: "Doodle",
    url: "https://doodle.com/login",
    email: "",
    password: "",
  },
  {
    app: "Q-Park",
    url: "",
    email: "",
    password: "",
  },
  {
    app: "EUIPO",
    url: "",
    email: "",
    password: "",
  },
  {
    app: "Hubstaff",
    url: "https://account.hubstaff.com/login",
    email: "nvtester@vipfy.store",
    password: "2020Vipfy!",
  },
];
